// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYuIHVSH5EpHNlMtJkKgCXGs3-1OyRFlg',
    appId: '1:1006453455654:web:9daafec59a7ff4513f9fe7',
    messagingSenderId: '1006453455654',
    projectId: 'fidelykey-safe-app',
    authDomain: 'fidelykey-safe-app.firebaseapp.com',
    storageBucket: 'fidelykey-safe-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-MphDoOkXARDoLaD4m_1FFjJj5aGCFY0',
    appId: '1:1006453455654:android:c98067996751be213f9fe7',
    messagingSenderId: '1006453455654',
    projectId: 'fidelykey-safe-app',
    storageBucket: 'fidelykey-safe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfOYpQyIwcMHAmgbiMXgmmU9Rbhceu4L0',
    appId: '1:1006453455654:ios:47e5c4310430e35b3f9fe7',
    messagingSenderId: '1006453455654',
    projectId: 'fidelykey-safe-app',
    storageBucket: 'fidelykey-safe-app.firebasestorage.app',
    iosBundleId: 'com.example.fidelyKey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfOYpQyIwcMHAmgbiMXgmmU9Rbhceu4L0',
    appId: '1:1006453455654:ios:47e5c4310430e35b3f9fe7',
    messagingSenderId: '1006453455654',
    projectId: 'fidelykey-safe-app',
    storageBucket: 'fidelykey-safe-app.firebasestorage.app',
    iosBundleId: 'com.example.fidelyKey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYuIHVSH5EpHNlMtJkKgCXGs3-1OyRFlg',
    appId: '1:1006453455654:web:4e24bbc381f2e92f3f9fe7',
    messagingSenderId: '1006453455654',
    projectId: 'fidelykey-safe-app',
    authDomain: 'fidelykey-safe-app.firebaseapp.com',
    storageBucket: 'fidelykey-safe-app.firebasestorage.app',
  );

}